AWSTemplateFormatVersion: "2010-09-09"
Description: "AWS CloudFormation template to create IAM role for SSM"

Resources:
  EC2SSMRole:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: "ec2-ssm-core"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service: "ec2.amazonaws.com"
            Action: "sts:AssumeRole"
      Policies:
        - PolicyName: "AmazonSSMManagedInstanceCore"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action:
                  - "ssm:UpdateInstanceInformation"
                  - "ssmmessages:CreateControlChannel"
                  - "ssmmessages:CreateDataChannel"
                  - "ssmmessages:OpenControlChannel"
                  - "ssmmessages:OpenDataChannel"
                Resource: "*"
